### ISSUE TITLE
Crash : NPE Tesselating block model

### ISSUE THREAD

**Issue by SpyMan10** [InfinityRaider/InfinityLib#16]
`Time: 1/15/17 6:27 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.func_188616_a(BakedInfBlockModel.java:65)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:101)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:53)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:290)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.func_188616_a(BakedInfBlockModel.java:65)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:101)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)

-- Block model being tesselated --
Details:
	Block: agricraft:crop
	Block location: World: (248,64,-1965), Chunk: (at 8,4,3 in 15,-123; contains blocks 240,0,-1968 to 255,255,-1953), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,0,-2048 to 511,255,-1537)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)

-- Block being tesselated --
Details:
	Block type: ID #331 (tile.agricraft:crop // com.infinityraider.agricraft.blocks.BlockCrop)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (248,64,-1965), Chunk: (at 8,4,3 in 15,-123; contains blocks 240,0,-1968 to 255,255,-1953), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,0,-2048 to 511,255,-1537)`

**Comment by InfinityRaider** [comment]
Closing since I am moving to 1.16 where this is no longer relevant.
