### ISSUE TITLE
essellatorBakedQuad.java:103 - Crash

### ISSUE THREAD

**Issue by SpyMan10** [InfinityRaider/InfinityLib#23]
java.lang.RuntimeException: ALREADY CONSTRUCTING VERTICES
	at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.startDrawing(TessellatorBakedQuad.java:103)
	at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.onStartDrawingQuadsCall(TessellatorBakedQuad.java:91)
	at com.infinityraider.infinitylib.render.tessellation.TessellatorAbstractBase.startDrawingQuads(TessellatorAbstractBase.java:90)
	at com.infinityraider.infinitylib.render.item.BakedInfItemModel.func_188616_a(BakedInfItemModel.java:54)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:166)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:141)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:204)
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:472)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:514)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:235)
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:303)
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_180450_b(RenderItemWrapper.java:284)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:538)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_146977_a(GuiMultiModule.java:229)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:96)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:512)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1409)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by InfinityRaider** [comment]
Closing since I am moving to 1.16 where this is no longer relevant.
