### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by vanFEK** [InfinityRaider/InfinityLib#45]
hello! when loading the world after generation, I get this crash:

```
Time: 15.03.22 17:40
Description: Tesselating liquid in world

java.lang.NullPointerException: Tesselating liquid in world
	at net.minecraft.client.renderer.FluidBlockRenderer.func_228796_a_(FluidBlockRenderer.java:409) ~[?:?] {re:classloading,xf:OptiFine:default}
	at com.infinityraider.infinitylib.render.fluid.InfFluidRenderer.func_228796_a_(InfFluidRenderer.java:40) ~[?:2.0.7] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_228794_a_(BlockRendererDispatcher.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_228794_a_(CCBlockRendererDispatcher.java:100) ~[?:1.16.5-4.0.7.445] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:858) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:734) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:191) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.betterf3.json:chunk.ChunkRenderDispatcherAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$17982/1942884319.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.FluidBlockRenderer.func_228796_a_(FluidBlockRenderer.java:409) ~[?:?] {re:classloading,xf:OptiFine:default}
	at com.infinityraider.infinitylib.render.fluid.InfFluidRenderer.func_228796_a_(InfFluidRenderer.java:40) ~[?:2.0.7] {re:classloading,pl:runtimedistcleaner:A}
-- Block being tesselated --
Details:
	Block location: World: (2,62,0), Chunk: (at 2,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_228794_a_(BlockRendererDispatcher.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_228794_a_(CCBlockRendererDispatcher.java:100) ~[?:1.16.5-4.0.7.445] {re:classloading}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['vanFEK'/187, l='ClientLevel', x=11.50, y=63.00, z=13.50]]
	Chunk stats: Client Chunk Cache: 121, 49
	Level dimension: minecraft:overworld
	Level spawn location: World: (2,63,10), Chunk: (at 2,3,10 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 64 game time, 64 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:197) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.betterf3.json:chunk.ChunkRenderDispatcherAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$17992/999130259.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5160516744 bytes (4921 MB) / 7147094016 bytes (6816 MB) up to 7147094016 bytes (6816 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmn128M -Xmx6806M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.29.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.29
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
```

**Comment by InfinityRaider** [comment]
Opticien...

**Comment by InfinityRaider** [comment]
Optifine...
