### ISSUE TITLE
"Could not increment priorities, priority field not retrieved" error spam

### ISSUE THREAD

**Issue by stepa2** [InfinityRaider/InfinityLib#51]
On Minecraft server with mohist-1.16.5-1040.
InfinityLib version 2.0.7

```
$ java --version
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
```

```
[13:06:02 ERROR]: [infinitylib]Could not retrieve Priority field from PrioritizedGoal.class
[13:06:02 WARN]: java.lang.NoSuchFieldException: modifiers
[13:06:02 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2416)
[13:06:02 WARN]:        at com.infinityraider.infinitylib.utility.EntityHelper.initPriorityField(EntityHelper.java:77)
[13:06:02 WARN]:        at com.infinityraider.infinitylib.utility.EntityHelper.<clinit>(EntityHelper.java:58)
[13:06:02 WARN]:        at com.infinityraider.agricraft.plugins.minecraft.GeneAnimalAttractant.onEntitySpawned(GeneAnimalAttractant.java:166)
[13:06:02 WARN]:        at net.minecraftforge.eventbus.ASMEventHandler_2004_GeneAnimalAttractant_onEntitySpawned_EntityJoinWorldEvent.invoke(.dynamic)
[13:06:02 WARN]:        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[13:06:02 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[13:06:02 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[13:06:02 WARN]:        at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:1093)
[13:06:02 WARN]:        at net.minecraft.world.server.ChunkManager.lambda$protoChunkToFullChunk$25(ChunkManager.java:621)
[13:06:02 WARN]:        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[13:06:02 WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[13:06:02 WARN]:        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[13:06:02 WARN]:        at net.minecraft.world.server.ChunkManager.func_219193_a_(ChunkManager.java:596)
[13:06:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
[13:06:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[13:06:02 WARN]:        at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
[13:06:02 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[13:06:02 WARN]:        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:592)
[13:06:02 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[13:06:02 WARN]:        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:600)
[13:06:02 WARN]:        at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:305)
[13:06:02 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:927)
[13:06:02 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:916)
[13:06:02 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:114)
[13:06:02 WARN]:        at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:895)
[13:06:02 WARN]:        at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:520)
[13:06:02 WARN]:        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:351)
[13:06:02 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221)
[13:06:02 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771)
[13:06:02 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[13:06:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by InfinityRaider** [comment]
Update to Java 16 or 17 and check if it still happens

**Comment by stepa2** [comment]
Yes, it still spams

**Comment by stepa2** [comment]
```
[14:02:39 ERROR]: [infinitylib]Could not retrieve Priority field from PrioritizedGoal.class
[14:02:39 WARN]: java.lang.NoSuchFieldException: modifiers
[14:02:39 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[14:02:39 WARN]:        at com.infinityraider.infinitylib.utility.EntityHelper.initPriorityField(EntityHelper.java:77)
[14:02:39 WARN]:        at com.infinityraider.infinitylib.utility.EntityHelper.<clinit>(EntityHelper.java:58)
[14:02:39 WARN]:        at com.infinityraider.agricraft.plugins.minecraft.GeneAnimalAttractant.onEntitySpawned(GeneAnimalAttractant.java:166)
[14:02:39 WARN]:        at net.minecraftforge.eventbus.ASMEventHandler_2006_GeneAnimalAttractant_onEntitySpawned_EntityJoinWorldEvent.invoke(.dynamic)
[14:02:39 WARN]:        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[14:02:39 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[14:02:39 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[14:02:39 WARN]:        at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:1093)
[14:02:39 WARN]:        at net.minecraft.world.server.ChunkManager.lambda$protoChunkToFullChunk$25(ChunkManager.java:621)
[14:02:39 WARN]:        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[14:02:39 WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[14:02:39 WARN]:        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[14:02:39 WARN]:        at net.minecraft.world.server.ChunkManager.func_219193_a_(ChunkManager.java:596)
[14:02:39 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[14:02:39 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[14:02:39 WARN]:        at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
[14:02:39 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[14:02:39 WARN]:        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:592)
[14:02:39 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[14:02:39 WARN]:        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:600)
[14:02:39 WARN]:        at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:305)
[14:02:39 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:927)
[14:02:39 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:916)
[14:02:39 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:114)
[14:02:39 WARN]:        at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:895)
[14:02:39 WARN]:        at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:520)
[14:02:39 WARN]:        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:351)
[14:02:39 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221)
[14:02:39 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771)
[14:02:39 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[14:02:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LisusIO** [comment]
me too

**Comment by Dokman** [comment]
i have the same too
